# Generated by Django 4.0.5 on 2022-06-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmgcalc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
