# Generated by Django 4.0.5 on 2022-06-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmgcalc', '0002_champion_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='armor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='attack_damage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='health_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='magic_resistance',
            field=models.IntegerField(default=0),
        ),
    ]
