# Generated by Django 4.0.5 on 2022-06-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmgcalc', '0003_champion_armour_champion_attack_damage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatedStatsWithLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.FloatField(default=1)),
                ('calc_health_points', models.FloatField(default=0)),
                ('calc_health_points_regen', models.FloatField(default=0)),
                ('calc_mana', models.FloatField(default=0)),
                ('calc_mana_regen', models.FloatField(default=0)),
                ('calc_armor', models.FloatField(default=0)),
                ('calc_magic_resistance', models.FloatField(default=0)),
                ('calc_attack_damage', models.FloatField(default=0)),
                ('calc_attack_speed', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='champion',
            name='armor',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='attack_damage',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='health_points',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='magic_resistance',
        ),
        migrations.AddField(
            model_name='champion',
            name='ability_haste',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='ability_power',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='armor_pen_flat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='armor_pen_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='armor_per_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='attack_damage_per_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='attack_speed_bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='attack_speed_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='attack_speed_windup',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='base_armor',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='base_attack_damage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='base_attack_speed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='base_crit_damage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='base_health_points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='base_health_regen',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='base_magic_resistance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='base_mana',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='base_mana_regen',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='crit_chance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='health_points_per_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='health_regen_per_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='life_steal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='magic_pen_flat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='magic_pen_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='magic_resistance_per_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='mana_per_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='mana_regen_per_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='movement_speed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='omnivamp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='physical_vamp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='champion',
            name='tenacity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='champion',
            name='level',
            field=models.FloatField(default=1),
        ),
    ]
