# Generated by Django 4.0.5 on 2022-06-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmgcalc', '0004_calculatedstatswithlevel_remove_champion_armor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abilityName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FinalChampionStatsWithLevelItemsRunes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.FloatField(default=1)),
                ('health_points', models.FloatField(default=0)),
                ('health_points_regen', models.FloatField(default=0)),
                ('mana', models.FloatField(default=0)),
                ('mana_regen', models.FloatField(default=0)),
                ('armor', models.FloatField(default=0)),
                ('magic_resistance', models.FloatField(default=0)),
                ('attack_damage', models.FloatField(default=0)),
                ('crit_damage', models.FloatField(default=0)),
                ('crit_chance', models.FloatField(default=0)),
                ('armor_pen_percentage', models.FloatField(default=0)),
                ('armor_pen_flat', models.FloatField(default=0)),
                ('ability_power', models.FloatField(default=0)),
                ('ability_haste', models.FloatField(default=0)),
                ('magic_pen_percentage', models.FloatField(default=0)),
                ('magic_pen_flat', models.FloatField(default=0)),
                ('movement_speed', models.FloatField(default=0)),
                ('attack_speed', models.FloatField(default=0)),
                ('attack_speed_windup', models.FloatField(default=0)),
                ('tenacity', models.FloatField(default=0)),
                ('life_steal', models.FloatField(default=0)),
                ('physical_vamp', models.FloatField(default=0)),
                ('omnivamp', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Runes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runeName', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='champion',
            name='ability_haste',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='ability_power',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='armor_pen_flat',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='armor_pen_percentage',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='crit_chance',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='life_steal',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='magic_pen_flat',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='magic_pen_percentage',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='movement_speed',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='omnivamp',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='physical_vamp',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='tenacity',
        ),
    ]
