# Generated by Django 4.0.5 on 2022-06-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmgcalc', '0005_abilities_finalchampionstatswithlevelitemsrunes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_damage_dealt', models.FloatField(default=0)),
                ('magical_damage_dealt', models.FloatField(default=0)),
                ('true_damage_dealt', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion_index', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('item1_index', models.IntegerField(default=0)),
                ('item2_index', models.IntegerField(default=0)),
                ('item3_index', models.IntegerField(default=0)),
                ('item4_index', models.IntegerField(default=0)),
                ('item5_index', models.IntegerField(default=0)),
                ('item6_index', models.IntegerField(default=0)),
                ('ability_q_level_index', models.IntegerField(default=0)),
                ('ability_w_level_index', models.IntegerField(default=0)),
                ('ability_e_level_index', models.IntegerField(default=0)),
                ('ability_r_level_index', models.IntegerField(default=0)),
                ('rune_keystone_index', models.IntegerField(default=0)),
                ('rune_primary1_index', models.IntegerField(default=0)),
                ('rune_primary2_index', models.IntegerField(default=0)),
                ('rune_primary3_index', models.IntegerField(default=0)),
                ('rune_secondary1_index', models.IntegerField(default=0)),
                ('rune_secondary2_index', models.IntegerField(default=0)),
                ('ability1', models.IntegerField(default=0)),
                ('ability2', models.IntegerField(default=0)),
                ('ability3', models.IntegerField(default=0)),
                ('ability4', models.IntegerField(default=0)),
                ('ability5', models.IntegerField(default=0)),
                ('ability6', models.IntegerField(default=0)),
                ('ability7', models.IntegerField(default=0)),
                ('ability8', models.IntegerField(default=0)),
                ('ability9', models.IntegerField(default=0)),
                ('ability10', models.IntegerField(default=0)),
                ('ability11', models.IntegerField(default=0)),
                ('ability12', models.IntegerField(default=0)),
                ('ability13', models.IntegerField(default=0)),
                ('ability14', models.IntegerField(default=0)),
                ('ability15', models.IntegerField(default=0)),
                ('dummy_health_points', models.FloatField(default=0)),
                ('dummy_armor', models.FloatField(default=0)),
                ('dummy_magic_resistance', models.FloatField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='abilities',
            old_name='abilityName',
            new_name='ability_name',
        ),
        migrations.RenameField(
            model_name='champion',
            old_name='championName',
            new_name='champion_name',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='itemName',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='runes',
            old_name='runeName',
            new_name='rune_name',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='level',
        ),
        migrations.RemoveField(
            model_name='finalchampionstatswithlevelitemsrunes',
            name='level',
        ),
        migrations.AlterField(
            model_name='abilities',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='champion',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='items',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='runes',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
