# Generated by Django 4.0.5 on 2022-06-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmgcalc', '0006_damageoutput_userinput_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='is_legendary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='items',
            name='is_mythic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='items',
            name='item_stat_1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='items',
            name='item_stat_2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='items',
            name='item_stat_3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='items',
            name='item_stat_4',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='items',
            name='mythic_stats_1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='items',
            name='mythic_stats_2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='items',
            name='mythic_stats_3',
            field=models.FloatField(default=0),
        ),
    ]
