# Generated by Django 4.0.5 on 2022-06-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmgcalc', '0007_items_is_legendary_items_is_mythic_items_item_stat_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatedstatswithlevel',
            name='calc_crit_damage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calculatedstatswithlevel',
            name='champion_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
