# Generated by Django 4.0.5 on 2022-06-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmgcalc', '0008_calculatedstatswithlevel_calc_crit_damage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='gold_cost',
            field=models.IntegerField(default=0),
        ),
    ]
