# Generated by Django 4.0.5 on 2022-06-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmgcalc', '0010_remove_items_is_legendary_remove_items_is_mythic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_stat_mana',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='items',
            name='item_stat_mana_regen',
            field=models.FloatField(default=0),
        ),
    ]
