# Generated by Django 4.0.5 on 2022-06-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmgcalc', '0011_items_item_stat_mana_items_item_stat_mana_regen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='item_stat_crit_change',
            new_name='item_stat_crit_chance',
        ),
        migrations.AddField(
            model_name='items',
            name='item_stat_grievous_wounds',
            field=models.FloatField(default=0.0),
        ),
    ]
