# Generated by Django 4.0.5 on 2022-06-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmgcalc', '0014_rename_calc_attack_speed_calculatedstatswithlevel_calc_bonus_attack_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='base_movement_speed',
            field=models.FloatField(default=0),
        ),
    ]
