# Generated by Django 4.0.5 on 2022-07-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmgcalc', '0016_finalchampionstatswithlevelitemsrunes_champion_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalchampionstatswithlevelitemsrunes',
            name='champion_level',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='finalchampionstatswithlevelitemsrunes',
            name='item_name_five',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='finalchampionstatswithlevelitemsrunes',
            name='item_name_four',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='finalchampionstatswithlevelitemsrunes',
            name='item_name_one',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='finalchampionstatswithlevelitemsrunes',
            name='item_name_six',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='finalchampionstatswithlevelitemsrunes',
            name='item_name_three',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='finalchampionstatswithlevelitemsrunes',
            name='item_name_two',
            field=models.CharField(default='', max_length=200),
        ),
    ]
