# Generated by Django 4.0.5 on 2022-07-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmgcalc', '0017_finalchampionstatswithlevelitemsrunes_champion_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalchampionstatswithlevelitemsrunes',
            name='ability_e_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='finalchampionstatswithlevelitemsrunes',
            name='ability_q_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='finalchampionstatswithlevelitemsrunes',
            name='ability_r_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='finalchampionstatswithlevelitemsrunes',
            name='ability_w_level',
            field=models.FloatField(default=0),
        ),
    ]
