# Generated by Django 4.0.5 on 2022-07-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmgcalc', '0018_finalchampionstatswithlevelitemsrunes_ability_e_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='damageoutput',
            name='dummy_armor',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='damageoutput',
            name='dummy_hp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='damageoutput',
            name='dummy_mr',
            field=models.FloatField(default=0),
        ),
    ]
