# Generated by Django 4.0.5 on 2022-07-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmgcalc', '0019_damageoutput_dummy_armor_damageoutput_dummy_hp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalchampionstatswithlevelitemsrunes',
            name='base_armor',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='finalchampionstatswithlevelitemsrunes',
            name='base_attack_damage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='finalchampionstatswithlevelitemsrunes',
            name='base_health_points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='finalchampionstatswithlevelitemsrunes',
            name='base_health_points_regen',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='finalchampionstatswithlevelitemsrunes',
            name='base_magic_resistance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='finalchampionstatswithlevelitemsrunes',
            name='base_mana',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='finalchampionstatswithlevelitemsrunes',
            name='base_mana_regen',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='finalchampionstatswithlevelitemsrunes',
            name='bonus_armor',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='finalchampionstatswithlevelitemsrunes',
            name='bonus_attack_damage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='finalchampionstatswithlevelitemsrunes',
            name='bonus_health_points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='finalchampionstatswithlevelitemsrunes',
            name='bonus_magic_resistance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='finalchampionstatswithlevelitemsrunes',
            name='bonus_mana',
            field=models.FloatField(default=0),
        ),
    ]
