# Generated by Django 4.0.5 on 2022-07-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmgcalc', '0020_finalchampionstatswithlevelitemsrunes_base_armor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='damageoutput',
            name='ability1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='damageoutput',
            name='ability10',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='damageoutput',
            name='ability11',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='damageoutput',
            name='ability12',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='damageoutput',
            name='ability13',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='damageoutput',
            name='ability14',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='damageoutput',
            name='ability15',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='damageoutput',
            name='ability2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='damageoutput',
            name='ability3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='damageoutput',
            name='ability4',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='damageoutput',
            name='ability5',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='damageoutput',
            name='ability6',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='damageoutput',
            name='ability7',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='damageoutput',
            name='ability8',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='damageoutput',
            name='ability9',
            field=models.FloatField(default=0),
        ),
    ]
